### ISSUE TITLE
Meeting Room Dynamics

### ISSUE THREAD

**Issue by ngnigel99** [nus-cs2102-AY2122S1-XY-J-N/CS2102_Project#51]
Meeting Room Dynamics
When a meeting room has its capacity changed, any room booking after the change date with more participants
(including the employee who made the booking) will automatically be removed. This is regardless of whether they are
approved or not.
The date when the capacity is changed is assumed to be today but it will be part of the input

**Comment by lixiyuan416** [comment]
why are u assigning this to me?

**Comment by ngnigel99** [comment]
> why are u assigning this to me?

Cause it's completed right, can close if so

**Comment by lixiyuan416** [comment]
Then dunnit create issue this mod not cs2113t
